name: Java CI Basic

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install stable Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn install -Dcicd=true

      - name: Run Tests
        run: mvn test -Dcicd=true
