name: Java CI Basic

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure latest stable Chrome is installed
        run: |
          google-chrome --version

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn install -Dcicd=true

      - name: Run Tests
        run: mvn test -Dcicd=true
