name: Java CI Custom Suite

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Choose browser for automation suite:'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - edge
      suite:
        description: 'Choose automation suite:'
        required: true
        default: 'smokeSuite'
        type: choice
        options:
          - smokeSuite
          - regressionSuite

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install stable Chrome 126
        run: |
          sudo apt purge google-chrome-stable
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Run automation tests
        run: mvn clean install -Dcicd=true -Dbrowser=${{ github.event.inputs.browser }} -DsuiteXmlFile=suites/${{ github.event.inputs.suite }}.xml -P CustomSuite
