name: ATF Nightly Suite

on:
  schedule:
    - cron: '0 23 * * 1-5'  # Runs at 23:00 (11:00 PM) from Monday (1) to Friday (5)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Run automation tests
        run: mvn clean install -DciCd=true -Dbrowser=chrome -DsuiteXmlFile=suites/regressionSuite.xml -P CustomSuite