name: Nightly Regression Suite

on:
  schedule:
    - cron: '0 1 * * *' # Runs at 01:00 AM UTC every day
  workflow_dispatch:     # Allows manual triggering as well

jobs:
  nightly-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Display Chrome version
        run: chrome --version

      - name: Set Maven executable permission
        run: chmod +x mvnw

      - name: Run Regression Tests
        run: mvn clean install -Dcicd=true -Dbrowser=chrome -DsuiteXmlFile=suites/regressionSuite.xml -P CustomSuite
